# Generated by Django 3.2.25 on 2024-05-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
