# Generated by Django 3.2.25 on 2024-03-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
